package com.crud.example.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@Data  // generate getter/setter
@AllArgsConstructor
@NoArgsConstructor
@Entity  //Mandatory
@Table(name = "PRODUCT_TBL")
public class Hotel {
	
	@Id  //Mandatory
	@GeneratedValue	//AutoGenerated
	private int id;
	private String name;
	private int numberOfHeads;
	private double bill;
	private double duration;
	
	
}
